export async function handler() {
  return {
    statusCode: 200,
    body: JSON.stringify([
      {
        title: "",
        filename: "beta22.jpg",
        url: "/images/comics/beta22.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "c_px.jpg",
        url: "/images/comics/c_px.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "comic1.jpg",
        url: "/images/comics/comic1.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "comic2.jpg",
        url: "/images/comics/comic2.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "FaunPan.jpg",
        url: "/images/comics/FaunPan.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "gyAQ.jpg",
        url: "/images/comics/gyAQ.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "J.jpg",
        url: "/images/comics/J.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "p3_72dpi2.jpg",
        url: "/images/comics/p3_72dpi2.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "proliferation.jpg",
        url: "/images/comics/proliferation.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "q.jpg",
        url: "/images/comics/q.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "s0217_ps_Kadmon_137dpi.jpg",
        url: "/images/comics/s0217_ps_Kadmon_137dpi.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "sw2khfdx_137.jpg",
        url: "/images/comics/sw2khfdx_137.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
      {
        title: "",
        filename: "vaacus.jpg",
        url: "/images/comics/vaacus.jpg",
        detais: "",
        link: "",
        technique: "comics",
      },
    ]),
  };
}
